name: Build commit

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y build-essential libmxml-dev

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: benzin-linux-amd64-${{github.sha}}
          path: benzin
          if-no-files-found: error
